version: "3"
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: db_aji
        ports:
            - "27017:27017"
        networks:
            - mynetwork

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - mynetwork

    app:
        build: .
        container_name: app
        ports:
            - "3001:5000"
        env_file:
            - .env.docker
        depends_on:
            - mongo
            - redis
        environment:
            - MONGO_URI=mongodb://mongo:27017/db_aji
            - REDIS_HOST=redis
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
